name: awallpapers
description: A new Haroon Wallpaper project.
publish_to: 'none'
version: 3.1.0+3

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  permission_handler:
#  dio:
#  flutter_wallpaper_manager:
  flutter_file_downloader:
#  path_provider:
  get:
  cached_network_image:
#  flutter_spinkit:
  get_storage:
  flutter_staggered_grid_view:
#  carousel_slider:
  google_mobile_ads:
  shared_preferences:
  intl:
  async_wallpaper:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
#  ios: true
  image_path: "assets/app_icon.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app_icon.jpeg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/app_icon.jpeg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app_icon.jpeg"

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
